name: Weekly schedule to check for updates
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

env:
  COMPOSE_DOCKER_CLI_BUILD: 1

permissions:
  contents: write
  pull-requests: write

jobs:
  builder_images:
    strategy:
      matrix:
        include:
          - baseimage: rockylinux
            version: "9"
            arch: arm64
    env:
      IMAGETAG: builder-${{ matrix.baseimage }}:${{ matrix.version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Follow main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git fetch origin main
          git checkout main
          git pull origin main

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v4
        with:
          driver-opts: network=host

      - name: Build image
        uses: docker/build-push-action@v7
        with:
          context: docker/rpmtools
          platforms: 'linux/${{ matrix.arch }}'
          build-args: |
            BASEIMAGE=${{ matrix.baseimage }}:${{ matrix.version }}
          tags: ${{ env.IMAGETAG }}
          outputs: type=docker,dest=${{ runner.temp }}/myimage.tar

      - name: update to docker-compose v2
        run: |
          sudo apt-get install -y curl
          sudo curl -SL https://github.com/docker/compose/releases/download/v2.34.0/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: generate specs
        run: |
          docker-compose up specgen --exit-code-from specgen
        env:
          DOCKER_DEFAULT_PLATFORM: linux/${{ matrix.arch }}
          DOCKER_BUILDKIT: 1

      - name: check on changes
        id: changed_files
        run: |
          NUM_CHANGED_FILES=$(git status -s specs | wc -l)
          echo "Number of changed files: $NUM_CHANGED_FILES"
          echo "num_changed_files=$NUM_CHANGED_FILES" >> $GITHUB_OUTPUT

      - name: Generate App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Create PR with new spec
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          BRANCH_NAME="auto-update-$(date +%s)"
          
          git checkout -b $BRANCH_NAME
          git add specs
          git commit -m "chore: automatic update specs"
          git push https://x-access-token:${{ secrets.PAT_CREATOR }}@github.com/${{ github.repository }}.git $BRANCH_NAME

          PR_URL=$(gh pr create \
            --title "chore: Automated Update" \
            --body "Automated PR." \
            --head "$BRANCH_NAME" \
            --base "main")

          echo "PR_URL=$PR_URL" >> $GITHUB_ENV
        if: ${{ steps.changed_files.outputs.num_changed_files > 0 }}

      - name: Merge PR
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_APPROVER }}
        run: |
          gh pr merge --auto --squash --delete-branch "$PR_URL" || gh pr merge --squash --delete-branch "$PR_URL"

        if: ${{ steps.changed_files.outputs.num_changed_files > 0 }}

      - name: Approve PR
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_APPROVER }}
        run: gh pr review --approve "$PR_URL"
        if: ${{ steps.changed_files.outputs.num_changed_files > 0 }}

      - name: Wait for PR merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr checks --watch "$PR_URL"

          until [ "$(gh pr view "$PR_URL" --json state -q .state)" = "MERGED" ]; do
            echo "Wachten tot PR gemerged is..."
            sleep 3
          done
        if: ${{ steps.changed_files.outputs.num_changed_files > 0 }}

      - name: Wait for Release Drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sleep 5

          RUN_ID=$(gh run list \
            --workflow "Draft release on push to main" \
            --branch main \
            --limit 1 \
            --json databaseId \
            -q '.[0].databaseId')

          gh run watch "$RUN_ID" --exit-status
        if: ${{ steps.changed_files.outputs.num_changed_files > 0 }}

      - name: Find Draft Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DRAFT_TAG=""
          until [ -n "$DRAFT_TAG" ]; do
            DRAFT_TAG=$(gh release list --json tagName,isDraft -q '.[] | select(.isDraft == true) | .tagName' | head -n 1)
            if [ -z "$DRAFT_TAG" ]; then
              echo "Waiting another 5 sec. for draft release."
              sleep 5
            fi
          done

          echo "Draft release tag: $DRAFT_TAG"
          echo "DRAFT_TAG=$DRAFT_TAG" >> $GITHUB_ENV
        if: ${{ steps.changed_files.outputs.num_changed_files > 0 }}

      - name: Release Draft release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_APPROVER }}
        run: |
          gh release edit "$DRAFT_TAG" --draft=false
          echo "Release $DRAFT_TAG published!"
        if: ${{ steps.changed_files.outputs.num_changed_files > 0 }}
